#Probability in percent that block will change
walking-probability: 5
sprint-probability: 10
sneak-probability: 0

#List of replacements for block under player
under_replacements:
- 'GRASS>DIRT'
- 'DIRT>DIRT:1'
- 'SNOW>AIR'
- 'SNOW:1>SNOW'

#List of replacements for blocks above changed blocks
in_replacements:
- 'LONG_GRASS>AIR'
- 'LONG_GRASS:1>AIR'
- 'YELLOW_FLOWER>AIR'
- 'DOUBLE_PLANT>AIR'
- 'DOUBLE_PLANT:1>AIR'
- 'DOUBLE_PLANT:2>AIR'
- 'DOUBLE_PLANT:3>AIR'
- 'DOUBLE_PLANT:4>AIR'
- 'RED_MUSHROOM>AIR'
- 'BROWN_MUSHROOM>AIR'
- 'DEAD_BUSH>AIR'